Account.create_or_update(:id => 1,  :number => 10001, :type_of_account => "bank", :name => "Bank Account")
Account.create_or_update(:id => 2,  :number => 10002, :type_of_account => "credit_card", :name => "Credit Card")
Account.create_or_update(:id => 3,  :number => 10003, :type_of_account => "cash", :name => "Cash")
Account.create_or_update(:id => 4,  :number => 20001, :type_of_account => "expenses", :name => "COGS")
Account.create_or_update(:id => 5,  :number => 20002, :type_of_account => "expenses", :name => "Repair")
Account.create_or_update(:id => 6,  :number => 20003, :type_of_account => "expenses", :name => "Office Equipment")
Account.create_or_update(:id => 7,  :number => 20004, :type_of_account => "expenses", :name => "Office Supplies")
Account.create_or_update(:id => 8,  :number => 30001, :type_of_account => "income", :name => "Undeposited Sales")
Account.create_or_update(:id => 9,  :number => 30002, :type_of_account => "income", :name => "Receivables")
Account.create_or_update(:id => 10, :number => 30003, :type_of_account => "income", :name => "Deposited Sales")
